/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalEarningsPaid' : number,
  'totalTasksApproved' : bigint,
  'activeWorkers' : bigint,
  'totalTasksCreated' : bigint,
}
export interface Objective {
  'description' : string,
  'category' : string,
  'targetTaskCount' : bigint,
}
export interface PayoutRecord {
  'taskId' : bigint,
  'triggeredAt' : bigint,
  'worker' : Principal,
  'amount' : number,
}
export interface Task {
  'id' : bigint,
  'isAIWorker' : boolean,
  'status' : string,
  'title' : string,
  'submittedResult' : [] | [string],
  'difficulty' : string,
  'createdAt' : bigint,
  'description' : string,
  'claimedBy' : [] | [Principal],
  'rewardUSD' : number,
  'category' : string,
  'aiScore' : [] | [bigint],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimTask' : ActorMethod<[bigint], string>,
  'generateTasks' : ActorMethod<[], bigint>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getAvailableTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyTasks' : ActorMethod<[], Array<Task>>,
  'getObjectives' : ActorMethod<[], Array<Objective>>,
  'getPayoutHistory' : ActorMethod<[], Array<PayoutRecord>>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerStats' : ActorMethod<[], Array<[Principal, bigint, number]>>,
  'initializeDefaultObjectives' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setObjective' : ActorMethod<[string, string, bigint], string>,
  'submitTask' : ActorMethod<[bigint, string], string>,
  'triggerPayout' : ActorMethod<[bigint], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];