/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'isAIWorker' : IDL.Bool,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'submittedResult' : IDL.Opt(IDL.Text),
  'difficulty' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'claimedBy' : IDL.Opt(IDL.Principal),
  'rewardUSD' : IDL.Float64,
  'category' : IDL.Text,
  'aiScore' : IDL.Opt(IDL.Nat),
});
export const Analytics = IDL.Record({
  'totalEarningsPaid' : IDL.Float64,
  'totalTasksApproved' : IDL.Nat,
  'activeWorkers' : IDL.Nat,
  'totalTasksCreated' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Objective = IDL.Record({
  'description' : IDL.Text,
  'category' : IDL.Text,
  'targetTaskCount' : IDL.Nat,
});
export const PayoutRecord = IDL.Record({
  'taskId' : IDL.Nat,
  'triggeredAt' : IDL.Int,
  'worker' : IDL.Principal,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimTask' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'generateTasks' : IDL.Func([], [IDL.Nat], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getAvailableTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getObjectives' : IDL.Func([], [IDL.Vec(Objective)], ['query']),
  'getPayoutHistory' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'initializeDefaultObjectives' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setObjective' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'submitTask' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'triggerPayout' : IDL.Func([IDL.Nat], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'isAIWorker' : IDL.Bool,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'submittedResult' : IDL.Opt(IDL.Text),
    'difficulty' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'claimedBy' : IDL.Opt(IDL.Principal),
    'rewardUSD' : IDL.Float64,
    'category' : IDL.Text,
    'aiScore' : IDL.Opt(IDL.Nat),
  });
  const Analytics = IDL.Record({
    'totalEarningsPaid' : IDL.Float64,
    'totalTasksApproved' : IDL.Nat,
    'activeWorkers' : IDL.Nat,
    'totalTasksCreated' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Objective = IDL.Record({
    'description' : IDL.Text,
    'category' : IDL.Text,
    'targetTaskCount' : IDL.Nat,
  });
  const PayoutRecord = IDL.Record({
    'taskId' : IDL.Nat,
    'triggeredAt' : IDL.Int,
    'worker' : IDL.Principal,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimTask' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'generateTasks' : IDL.Func([], [IDL.Nat], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getAvailableTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getObjectives' : IDL.Func([], [IDL.Vec(Objective)], ['query']),
    'getPayoutHistory' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'initializeDefaultObjectives' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setObjective' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'submitTask' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'triggerPayout' : IDL.Func([IDL.Nat], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };